version: '3.8'
services:
  bot:
    build: ../trading-bot
    container_name: trading-bot
    env_file: .env
    volumes:
      - ./:/app
    command: ["python", "src/main.py", "--mode", "paper", "--config", "config.yaml", "--exchange", "pepperstone", "--symbol", "EUR/USD", "--timeframe", "15m", "--dry-run", "true"]
    ports:
      - "8000:8000"  # metrics endpoint
    restart: unless-stopped
